homepage: "https://www.7-zip.org/sdk.html"
language: c++
primary_contact: "ipavlov@users.sourceforge.net"
auto_ccs:
  - "mail@joachim-bauch.de"
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/fancycode/lzma-fuzz.git'
