homepage: "https://github.com/rust-lang/regex"
primary_contact: "jamslam@gmail.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "david@adalogics.com"
main_repo: 'https://github.com/rust-lang/regex'
