homepage: "https://www.gnu.org/software/binutils/"
language: c
primary_contact: "foo@bah.com"
vendor_ccs:
  - "foo@bah.com"
sanitizers:
  - address
main_repo: "https://github.com/bminor/binutils-gdb.git"
