homepage: "http://freeimage.sourceforge.net/"
language: c++
primary_contact: "drolon@infonie.fr"

sanitizers:
  - address
  - undefined

labels:
  load_from_memory_fuzzer:
    - sundew

main_repo: 'https://svn.code.sf.net/p/freeimage/svn/'
