homepage: "https://www.knot-dns.cz/"
language: c++
primary_contact: "knot.dns@gmail.com"
auto_ccs:
  - "jonathan.foote@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://gitlab.labs.nic.cz/knot/knot-dns'
